const express = require('express');
const auth = require('../middleware/auth');
const requireAdmin = require('../middleware/requireAdmin');
const dashboardController = require('../controllers/admin/dashboardController');
const sessionController = require('../controllers/admin/sessionController');
const userManagementController = require('../controllers/admin/userManagementController');
const teacherManagementController = require('../controllers/admin/teacherManagementController');
const auditLogController = require('../controllers/admin/auditLogController');
const questionManagementController = require('../controllers/admin/questionManagementController');
const academicTaxonomyController = require('../controllers/admin/academicTaxonomyController');
const bookManagementController = require('../controllers/admin/bookManagementController');
const contestManagementController = require('../controllers/admin/contestManagementController');
const ieltsManagementController = require('../controllers/admin/ieltsManagementController');
const noticeManagementController = require('../controllers/admin/noticeManagementController');
const waitlistManagementController = require('../controllers/admin/waitlistManagementController');
const moderationManagementController = require('../controllers/admin/moderationManagementController');
const communicationsManagementController = require('../controllers/admin/communicationsManagementController');

const router = express.Router();

router.use(auth, requireAdmin);

router.get('/session', sessionController.getAdminSession);
router.get('/dashboard/stats', dashboardController.getDashboardStats);
router.get('/users', userManagementController.listUsers);
router.get('/users/:userId', userManagementController.getUserDetails);
router.patch('/users/:userId/role', userManagementController.updateUserRole);
router.patch('/users/:userId/status', userManagementController.updateUserStatus);
router.get('/teachers', teacherManagementController.listTeachers);
router.get('/teachers/:userId', teacherManagementController.getTeacherDetails);
router.patch('/teachers/:userId/application', teacherManagementController.updateTeacherApplicationStatus);
router.patch('/teachers/:userId/verification', teacherManagementController.updateTeacherVerificationStatus);
router.get('/questions', questionManagementController.listQuestions);
router.get('/questions/reports', questionManagementController.listQuestionReports);
router.get('/questions/quality', questionManagementController.getQuestionQualityStats);
router.get('/questions/:questionId', questionManagementController.getQuestionDetails);
router.patch('/questions/:questionId/approve', questionManagementController.approveQuestion);
router.patch('/questions/:questionId/reject', questionManagementController.rejectQuestion);
router.patch('/questions/:questionId', questionManagementController.editQuestion);
router.patch('/questions/reports/:questionId/status', questionManagementController.updateQuestionReportStatus);
router.get('/books', bookManagementController.listBooks);
router.get('/books/:bookId', bookManagementController.getBookDetails);
router.patch('/books/:bookId/approve', bookManagementController.approveBook);
router.patch('/books/:bookId/reject', bookManagementController.rejectBook);
router.get('/contests', contestManagementController.listContests);
router.post('/contests', contestManagementController.createContest);
router.get('/contests/live/summary', contestManagementController.getLiveContestSummary);
router.get('/contests/live/participants', contestManagementController.getLiveContestParticipants);
router.get('/contests/anti-cheat', contestManagementController.getSuspiciousAttempts);
router.get('/contests/anti-cheat/:resultId', contestManagementController.getAttemptDetails);
router.patch('/contests/anti-cheat/:resultId/flag', contestManagementController.flagAttempt);
router.patch('/contests/anti-cheat/:resultId/clear', contestManagementController.clearAttemptFlag);
router.patch('/contests/anti-cheat/:resultId/review-note', contestManagementController.addAttemptReviewNote);
router.get('/contests/:contestId', contestManagementController.getContestDetails);
router.patch('/contests/:contestId', contestManagementController.updateContest);
router.patch('/contests/:contestId/cancel', contestManagementController.cancelContest);
router.patch('/contests/:contestId/archive', contestManagementController.archiveContest);
router.get('/content/ielts-sets', ieltsManagementController.listIeltsSets);
router.get('/content/ielts-sets/:setType(listening|writing)/:setId', ieltsManagementController.getIeltsSetDetails);
router.patch('/content/ielts-sets/:setType(listening|writing)/:setId/approve', ieltsManagementController.approveIeltsSet);
router.patch('/content/ielts-sets/:setType(listening|writing)/:setId/reject', ieltsManagementController.rejectIeltsSet);
router.get('/content/notices', noticeManagementController.listNotices);
router.post('/content/notices', noticeManagementController.createNotice);
router.patch('/content/notices/:noticeId', noticeManagementController.updateNotice);
router.patch('/content/notices/:noticeId/archive', noticeManagementController.archiveNotice);
router.get('/content/waitlist', waitlistManagementController.listWaitlistEntries);
router.get('/content/waitlist/export', waitlistManagementController.exportWaitlistEntries);
router.patch('/content/waitlist/:entryId/contacted', waitlistManagementController.markWaitlistContacted);
router.get('/audit-logs', auditLogController.getAuditLogs);
router.get('/notifications/stats', communicationsManagementController.getNotificationAudienceStats);
router.get('/notifications/broadcasts', communicationsManagementController.listBroadcasts);
router.post('/notifications/broadcasts', communicationsManagementController.createBroadcast);
router.get('/support/tickets', communicationsManagementController.listSupportTickets);
router.get('/support/tickets/:ticketId', communicationsManagementController.getSupportTicketDetails);
router.patch('/support/tickets/:ticketId/status', communicationsManagementController.updateSupportTicketStatus);
router.patch('/support/tickets/:ticketId/priority', communicationsManagementController.updateSupportTicketPriority);
router.post('/support/tickets/:ticketId/reply', communicationsManagementController.replyToSupportTicket);
router.patch('/support/tickets/:ticketId/note', communicationsManagementController.addSupportTicketNote);
router.get('/support/feedback', communicationsManagementController.listFeedbackEntries);
router.get('/support/feedback/:feedbackId', communicationsManagementController.getFeedbackDetails);
router.patch('/support/feedback/:feedbackId/status', communicationsManagementController.updateFeedbackStatus);
router.patch('/support/feedback/:feedbackId/note', communicationsManagementController.addFeedbackNote);
router.get('/moderation/reports', moderationManagementController.listReports);
router.get('/moderation/reports/:reportId', moderationManagementController.getReportDetails);
router.patch('/moderation/reports/:reportId/under-review', moderationManagementController.markReportUnderReview);
router.patch('/moderation/reports/:reportId/dismiss', moderationManagementController.dismissReport);
router.patch('/moderation/reports/:reportId/resolve', moderationManagementController.resolveReport);
router.patch('/moderation/reports/:reportId/note', moderationManagementController.addReportNote);
router.patch('/moderation/reports/:reportId/warn', moderationManagementController.warnReportedUser);
router.patch('/moderation/reports/:reportId/hide', moderationManagementController.hideReportedContent);
router.patch('/moderation/reports/:reportId/user-status', moderationManagementController.updateReportedUserStatus);
router.get('/moderation/appeals', moderationManagementController.listAppeals);
router.get('/moderation/appeals/:appealId', moderationManagementController.getAppealDetails);
router.patch('/moderation/appeals/:appealId/approve', moderationManagementController.approveAppeal);
router.patch('/moderation/appeals/:appealId/reject', moderationManagementController.rejectAppeal);
router.patch('/moderation/appeals/:appealId/note', moderationManagementController.addAppealNote);
router.get('/academic-taxonomy/tree', academicTaxonomyController.getTaxonomyTree);
router.post('/academic-taxonomy/:type(subjects|papers|chapters|topics)', academicTaxonomyController.createTaxonomyNode);
router.patch('/academic-taxonomy/:type(subjects|papers|chapters|topics)/:nodeId', academicTaxonomyController.updateTaxonomyNode);
router.patch('/academic-taxonomy/:type(subjects|papers|chapters|topics)/:nodeId/archive', academicTaxonomyController.archiveTaxonomyNode);
router.patch('/academic-taxonomy/:type(subjects|papers|chapters|topics)/:nodeId/reorder', academicTaxonomyController.reorderTaxonomyNode);

module.exports = router;
