const StudyRoutine = require('../models/StudyRoutine');
const StudySession = require('../models/StudySession');
const { backfillDates, generateDayPlan, toISODate, startOfDay } = require('../utils/recurrence');

function userIdFrom(req) {
  return req.user._id || req.user.id;
}

/**
 * Normalize an incoming routine so dayDate / startAt / endAt are stored as
 * proper Date objects even if the client (or AI) sent ISO strings. Also
 * defaults priority / estimatedMinutes when missing.
 */
function normalizeRoutine(routine) {
  if (!Array.isArray(routine)) return [];
  return routine.map((day) => {
    const out = { ...day };
    if (out.dayDate) {
      const d = new Date(out.dayDate);
      out.dayDate = isNaN(d.getTime()) ? null : d;
    }
    if (Array.isArray(out.segments)) {
      out.segments = out.segments.map((seg) => {
        const s = { ...seg };
        if (s.startAt) {
          const d = new Date(s.startAt);
          s.startAt = isNaN(d.getTime()) ? null : d;
        }
        if (s.endAt) {
          const d = new Date(s.endAt);
          s.endAt = isNaN(d.getTime()) ? null : d;
        }
        if (s.priority && !['high', 'medium', 'low'].includes(s.priority)) {
          s.priority = 'medium';
        }
        if (typeof s.completed !== 'boolean') s.completed = false;
        return s;
      });
    }
    return out;
  });
}

exports.getRoutine = async (req, res, next) => {
  try {
    const routine = await StudyRoutine.findOne({ userId: userIdFrom(req) });
    res.status(200).json({
      success: true,
      data: { routine }
    });
  } catch (err) {
    next(err);
  }
};

function normalizeStudentProfile(profile) {
  if (!profile || typeof profile !== 'object') return {};
  const out = { ...profile };
  if (out.planDurationDays === undefined && out.plan_duration_days !== undefined) {
    out.planDurationDays = out.plan_duration_days;
  }
  if (out.studyDaysPerWeek === undefined && out.study_days_per_week !== undefined) {
    out.studyDaysPerWeek = out.study_days_per_week;
  }
  return out;
}

/**
 * Merge AI-generated routine days into a full skeleton generated by
 * generateDayPlan().  This guarantees the routine has exactly durationDays
 * entries, even when the LLM only emits a partial set of days.
 *
 * The returned days carry an `isRest` flag so downstream code can
 * distinguish between days that are intentionally rest days and days
 * that are study days the AI simply omitted.
 *
 * @param {Array} routine  raw AI-returned days (can be partial)
 * @param {Object} opts
 * @param {Date|string}  [opts.startDate]
 * @param {number}       [opts.durationDays=30]
 * @param {number}       [opts.studyDaysPerWeek=7]
 * @returns {Array} merged routine with exactly durationDays entries
 */
function ensureFullRoutine(routine, { startDate, durationDays, studyDaysPerWeek } = {}) {
  const planDurationDays = Number.isFinite(durationDays) ? durationDays : 30;
  const perWeek = Math.min(7, Math.max(1, Number(studyDaysPerWeek) || 7));

  let resolvedStartDate = startDate;
  if (!resolvedStartDate && routine.length > 0 && routine[0].dayDate) {
    resolvedStartDate = toISODate(routine[0].dayDate);
  }

  const skeleton = generateDayPlan({
    startDate: resolvedStartDate || new Date(),
    durationDays: planDurationDays,
    studyDaysPerWeek: perWeek
  });
  if (skeleton.length === 0) return routine;

  // Index AI days by ISO date key
  const aiByDate = {};
  for (const day of routine) {
    const key = day.dayDate ? toISODate(day.dayDate) : null;
    if (key) aiByDate[key] = day;
  }

  // Merge: for each skeleton slot, use AI segments when present and non-empty.
  // Study days the AI left empty are still marked study (isRest=false) so
  // downstream code can fill them.
  return skeleton.map((sk) => {
    const aiDay = aiByDate[sk.dayDate];
    const hasAiSegments = aiDay && Array.isArray(aiDay.segments) && aiDay.segments.length > 0;

    if (hasAiSegments) {
      return {
        ...aiDay,
        day: aiDay.day || sk.day,
        dayDate: sk.dayDate + 'T00:00:00.000Z',
        isRest: false
      };
    }
    // Rest day from skeleton or study day AI didn't fill
    return {
      day: sk.day,
      dayDate: sk.dayDate + 'T00:00:00.000Z',
      segments: [],
      isRest: sk.isRest
    };
  });
}

/**
 * Fill study days that have no segments with auto-generated content.
 * Study days (isRest === false) with empty segments array get
 * meaningful study blocks constructed from the exam-info subject list.
 * The segments are created WITHOUT startAt/endAt so backfillDates()
 * fills in correct timestamps later.
 *
 * @param {Array}  routine   full routine array (from ensureFullRoutine)
 * @param {Object} examInfo  exam info containing subjects[]
 * @param {string|null} [cutoffKey] ISO YYYY-MM-DD. When provided, only empty
 *        study days on or before this date are filled. Days after it are left
 *        as empty placeholders so the week-by-week "Generate Next Week" flow
 *        can fill them later. When null, every empty study day is filled.
 * @returns {Array} same routine with study-day segments filled
 */
function fillEmptyStudyDays(routine, examInfo, cutoffKey = null) {
  if (!Array.isArray(routine)) return routine;

  // Build a flat list of (subject, paper, chapter) to cycle through
  const subjects = examInfo?.subjects || [];
  const chapterList = [];
  for (const subj of subjects) {
    const name = subj.name || 'Study';
    const paper = subj.paper || '';
    const chapters = Array.isArray(subj.chapters) && subj.chapters.length > 0
      ? subj.chapters
      : [''];
    for (const chapter of chapters) {
      chapterList.push({
        subject: name,
        paper,
        chapter,
        task: chapter
          ? `Study and practice ${name} — ${chapter}`
          : `Review and practice ${name}`
      });
    }
  }

  // No subject data — give each empty study day a generic block
  const fallbackSegments = [
    { subject: 'Morning Routine', paper: '', chapter: '', task: 'Wake up, freshen up', priority: 'low', estimatedMinutes: 30 },
    { subject: 'Study', paper: '', chapter: '', task: 'Review notes and practice problems', priority: 'medium', estimatedMinutes: 90 },
    { subject: 'Break', paper: '', chapter: '', task: 'Short rest, snack', priority: 'low', estimatedMinutes: 15 },
    { subject: 'Study', paper: '', chapter: '', task: 'Continue practice and revision', priority: 'medium', estimatedMinutes: 90 },
    { subject: 'Break', paper: '', chapter: '', task: 'Rest, recharge', priority: 'low', estimatedMinutes: 15 },
    { subject: 'Study', paper: '', chapter: '', task: 'Review weak areas', priority: 'medium', estimatedMinutes: 90 },
    { subject: 'Study', paper: '', chapter: '', task: 'Solve previous questions', priority: 'medium', estimatedMinutes: 90 }
  ];

  let chIdx = 0;
  return routine.map((day) => {
    if (day.isRest) return day;
    const segs = Array.isArray(day.segments) ? day.segments : [];
    if (segs.length > 0) return day;

    // Week-by-week mode: leave days past the cutoff as empty placeholders so
    // the student generates them later via "Generate Next Week".
    if (cutoffKey) {
      const key = day.dayDate ? toISODate(day.dayDate) : null;
      if (key && key > cutoffKey) return day;
    }

    const newSegs = [];
    newSegs.push({
      subject: 'Morning Routine',
      paper: '',
      chapter: '',
      task: 'Wake up, freshen up',
      priority: 'low',
      estimatedMinutes: 30
    });

    if (chapterList.length > 0) {
      for (let block = 0; block < 6; block++) {
        const item = chapterList[chIdx % chapterList.length];
        chIdx++;
        newSegs.push({
          subject: item.subject,
          paper: item.paper,
          chapter: item.chapter,
          task: item.task,
          priority: 'medium',
          estimatedMinutes: 90
        });
        if (block < 5 && (block + 1) % 2 === 0) {
          newSegs.push({
            subject: 'Break',
            paper: '',
            chapter: '',
            task: 'Short rest, recharge',
            priority: 'low',
            estimatedMinutes: 15
          });
        }
      }
    } else {
      newSegs.push(...fallbackSegments.map((s) => ({ ...s })));
    }

    return { ...day, segments: newSegs };
  });
}

exports.saveRoutine = async (req, res, next) => {
  try {
    const { routine, examInfo, studentProfile, startDate, durationDays } = req.body;
    if (!routine || !Array.isArray(routine)) {
      return res.status(400).json({ success: false, message: 'Invalid routine format' });
    }
    const userId = userIdFrom(req);
    const normalizedProfile = normalizeStudentProfile(studentProfile);

    // Ensure the routine has exactly durationDays entries
    const fullRoutine = ensureFullRoutine(routine, {
      startDate,
      durationDays: durationDays || normalizedProfile.planDurationDays,
      studyDaysPerWeek: normalizedProfile.studyDaysPerWeek
    });

    // Resolve the plan start/end dates up front so we can scope generation to
    // the FIRST WEEK only. The student generates the rest of the plan one week
    // at a time (each week adapts to the prior week's progress).
    const resolvedStart = startDate
      ? new Date(startDate)
      : (fullRoutine[0]?.dayDate ? new Date(fullRoutine[0].dayDate) : null);
    const resolvedDuration =
      durationDays && Number.isFinite(durationDays)
        ? durationDays
        : (normalizedProfile?.planDurationDays || 30);
    let planEnd = null;
    if (resolvedStart && !isNaN(resolvedStart.getTime())) {
      planEnd = new Date(resolvedStart);
      planEnd.setUTCDate(planEnd.getUTCDate() + resolvedDuration - 1);
    }

    // The first week ends 6 days after the start (clamped to the plan end for
    // very short plans). Only days up to this boundary get filled now; later
    // days stay empty until "Generate Next Week" is used.
    let firstWeekEnd = null;
    if (resolvedStart && !isNaN(resolvedStart.getTime())) {
      firstWeekEnd = new Date(resolvedStart);
      firstWeekEnd.setUTCDate(firstWeekEnd.getUTCDate() + 6);
      if (planEnd && firstWeekEnd > planEnd) firstWeekEnd = new Date(planEnd);
    }
    const firstWeekKey = firstWeekEnd ? toISODate(firstWeekEnd) : null;

    const filled = fillEmptyStudyDays(fullRoutine, examInfo, firstWeekKey);
    const normalized = backfillDates(normalizeRoutine(filled), {
      wakeUpHour: 7,
      defaultSegmentMinutes: 90,
      timezoneOffsetHours: 6
    });

    let studyRoutine = await StudyRoutine.findOne({ userId });
    if (studyRoutine) {
      studyRoutine.routine = normalized;
      if (examInfo) studyRoutine.examInfo = examInfo;
      if (normalizedProfile) studyRoutine.studentProfile = normalizedProfile;
      if (resolvedStart && !isNaN(resolvedStart.getTime())) {
        studyRoutine.startDate = resolvedStart;
      }
      if (durationDays && Number.isFinite(durationDays)) {
        studyRoutine.durationDays = durationDays;
      }
      // Auto-derive exam date if missing (fallback: startDate + durationDays)
      if (!studyRoutine.examInfo?.examDate && studyRoutine.startDate && studyRoutine.durationDays) {
        const examD = new Date(studyRoutine.startDate);
        examD.setUTCDate(examD.getUTCDate() + studyRoutine.durationDays);
        studyRoutine.examInfo = {
          ...(studyRoutine.examInfo || {}),
          examDate: examD,
          examName: studyRoutine.examInfo?.examName || 'Auto-derived'
        };
      }
      // Mark only the FIRST WEEK as generated. Days past this remain empty
      // placeholders, so the "Generate Next Week" button appears and the
      // following week adapts to this week's progress.
      if (firstWeekEnd) studyRoutine.generatedUpTo = firstWeekEnd;
      await studyRoutine.save();
    } else {
      studyRoutine = await StudyRoutine.create({
        userId,
        routine: normalized,
        examInfo: examInfo || {},
        studentProfile: normalizedProfile || {},
        startDate: resolvedStart && !isNaN(resolvedStart.getTime()) ? resolvedStart : null,
        durationDays: resolvedDuration,
        generatedUpTo: firstWeekEnd
      });
    }

    res.status(200).json({
      success: true,
      data: { routine: studyRoutine }
    });
  } catch (err) {
    next(err);
  }
};

exports.toggleSegment = async (req, res, next) => {
  try {
    const { dayId, segmentId, completed } = req.body;
    const userId = userIdFrom(req);

    const studyRoutine = await StudyRoutine.findOne({ userId });
    if (!studyRoutine) {
      return res.status(404).json({ success: false, message: 'Routine not found' });
    }

    const day = studyRoutine.routine.id(dayId);
    if (!day) {
      return res.status(404).json({ success: false, message: 'Day not found' });
    }

    const segment = day.segments.id(segmentId);
    if (!segment) {
      return res.status(404).json({ success: false, message: 'Segment not found' });
    }

    segment.completed = !!completed;
    await studyRoutine.save();

    res.status(200).json({
      success: true,
      data: { routine: studyRoutine }
    });
  } catch (err) {
    next(err);
  }
};

// Manual edit of a single segment's fields
exports.updateSegment = async (req, res, next) => {
  try {
    const { dayId, segmentId, fields } = req.body;
    const userId = userIdFrom(req);

    if (!fields || typeof fields !== 'object') {
      return res.status(400).json({ success: false, message: 'fields object is required' });
    }

    const studyRoutine = await StudyRoutine.findOne({ userId });
    if (!studyRoutine) {
      return res.status(404).json({ success: false, message: 'Routine not found' });
    }

    const day = studyRoutine.routine.id(dayId);
    if (!day) {
      return res.status(404).json({ success: false, message: 'Day not found' });
    }

    const segment = day.segments.id(segmentId);
    if (!segment) {
      return res.status(404).json({ success: false, message: 'Segment not found' });
    }

    // Update only allowed fields (backwards-compatible with old client)
    const allowed = ['time', 'subject', 'paper', 'chapter', 'task', 'startAt', 'endAt', 'priority', 'estimatedMinutes'];
    for (const key of allowed) {
      if (fields[key] !== undefined) {
        if ((key === 'startAt' || key === 'endAt') && fields[key]) {
          const d = new Date(fields[key]);
          segment[key] = isNaN(d.getTime()) ? null : d;
        } else {
          segment[key] = fields[key];
        }
      }
    }
    await studyRoutine.save();

    res.status(200).json({
      success: true,
      data: { routine: studyRoutine }
    });
  } catch (err) {
    next(err);
  }
};

// Replace entire routine (used after AI modification)
exports.replaceRoutine = async (req, res, next) => {
  try {
    const { routine, startDate, durationDays } = req.body;
    if (!routine || !Array.isArray(routine)) {
      return res.status(400).json({ success: false, message: 'Invalid routine format' });
    }
    const userId = userIdFrom(req);

    const studyRoutine = await StudyRoutine.findOne({ userId });
    if (!studyRoutine) {
      return res.status(404).json({ success: false, message: 'Routine not found' });
    }

    // Read existing profile for studyDaysPerWeek
    const existingProfile = normalizeStudentProfile(studyRoutine.studentProfile);
    const fullRoutine = ensureFullRoutine(routine, {
      startDate: startDate || studyRoutine.startDate,
      durationDays: durationDays || studyRoutine.durationDays,
      studyDaysPerWeek: existingProfile.studyDaysPerWeek
    });

    // Preserve the week-by-week boundary: only fill empty study days up to the
    // already-generated cutoff. Days past it stay empty placeholders so the
    // "Generate Next Week" flow still works after an AI modification.
    const cutoffKey = studyRoutine.generatedUpTo ? toISODate(studyRoutine.generatedUpTo) : null;
    const filled = fillEmptyStudyDays(fullRoutine, studyRoutine.examInfo || {}, cutoffKey);
    const normalized = backfillDates(normalizeRoutine(filled), {
      wakeUpHour: 7,
      defaultSegmentMinutes: 90,
      timezoneOffsetHours: 6
    });

    studyRoutine.routine = normalized;
    if (startDate) {
      const d = new Date(startDate);
      if (!isNaN(d.getTime())) studyRoutine.startDate = d;
    }
    if (durationDays && Number.isFinite(durationDays)) {
      studyRoutine.durationDays = durationDays;
    }
    // generatedUpTo is intentionally left unchanged — a modification edits the
    // already-generated weeks; it does not generate new ones.
    await studyRoutine.save();

    res.status(200).json({
      success: true,
      data: { routine: studyRoutine }
    });
  } catch (err) {
    next(err);
  }
};

exports.deleteRoutine = async (req, res, next) => {
  try {
    const userId = userIdFrom(req);
    await StudyRoutine.deleteOne({ userId });
    await StudySession.deleteMany({ userId });
    res.status(200).json({
      success: true,
      message: 'Routine deleted successfully'
    });
  } catch (err) {
    next(err);
  }
};

/**
 * GET /stats
 * Returns aggregate tracking stats: streak, completion %, per-subject %
 */
exports.getStats = async (req, res, next) => {
  try {
    const userId = userIdFrom(req);
    const studyRoutine = await StudyRoutine.findOne({ userId }).lean();
    if (!studyRoutine) {
      return res.status(200).json({
        success: true,
        data: {
          streakDays: 0,
          todayCompletionPct: 0,
          overallCompletionPct: 0,
          bySubject: {},
          byDay: []
        }
      });
    }

    const today = toISODate(new Date());
    const days = Array.isArray(studyRoutine.routine) ? studyRoutine.routine : [];
    let totalSegments = 0;
    let doneSegments = 0;
    let todayDone = 0;
    let todayTotal = 0;
    const bySubject = {};
    const byDay = [];

    // Streak: walk most-recent days (today and earlier) backwards.
    // A "streak day" is a day with at least 1 segment AND all segments completed.
    const dayByDate = new Map();
    for (const day of days) {
      const key = day.dayDate ? toISODate(day.dayDate) : null;
      if (!key) continue;
      dayByDate.set(key, day);
    }

    for (const day of days) {
      const segs = Array.isArray(day.segments) ? day.segments : [];
      let dDone = 0;
      for (const seg of segs) {
        totalSegments++;
        if (seg.completed) {
          doneSegments++;
          dDone++;
        }
        const subj = seg.subject || 'Other';
        if (!bySubject[subj]) bySubject[subj] = { planned: 0, done: 0, pct: 0 };
        bySubject[subj].planned++;
        if (seg.completed) bySubject[subj].done++;

        if (day.dayDate && toISODate(day.dayDate) === today) {
          todayTotal++;
          if (seg.completed) todayDone++;
        }
      }
      if (day.dayDate) {
        byDay.push({
          dayDate: toISODate(day.dayDate),
          day: day.day,
          planned: segs.length,
          done: dDone,
          pct: segs.length === 0 ? 0 : Math.round((dDone / segs.length) * 100)
        });
      }
    }

    for (const subj of Object.keys(bySubject)) {
      const s = bySubject[subj];
      s.pct = s.planned === 0 ? 0 : Math.round((s.done / s.planned) * 100);
    }

    // Streak: from today backward, while the day is fully complete.
    // Days with no segments (rest days) do not break the streak.
    let streakDays = 0;
    const cursor = new Date();
    cursor.setUTCHours(0, 0, 0, 0);
    for (let i = 0; i < 365; i++) {
      const probe = new Date(cursor);
      probe.setUTCDate(cursor.getUTCDate() - i);
      const key = toISODate(probe);
      const day = dayByDate.get(key);
      if (!day) break;
      const segs = Array.isArray(day.segments) ? day.segments : [];
      if (segs.length === 0) continue;
      const allDone = segs.every((s) => s.completed);
      if (allDone) streakDays++;
      else break;
    }

    res.status(200).json({
      success: true,
      data: {
        streakDays,
        todayCompletionPct: todayTotal === 0 ? 0 : Math.round((todayDone / todayTotal) * 100),
        overallCompletionPct: totalSegments === 0 ? 0 : Math.round((doneSegments / totalSegments) * 100),
        bySubject,
        byDay
      }
    });
  } catch (err) {
    next(err);
  }
};

// --- Phase 2 focus-mode session scaffolding ---

exports.startSession = async (req, res, next) => {
  try {
    const { dayId, segmentId } = req.body;
    if (!dayId || !segmentId) {
      return res.status(400).json({ success: false, message: 'dayId and segmentId required' });
    }
    const userId = userIdFrom(req);
    const routine = await StudyRoutine.findOne({ userId });
    if (!routine) return res.status(404).json({ success: false, message: 'Routine not found' });

    const session = await StudySession.create({
      userId,
      routineId: routine._id,
      dayId,
      segmentId,
      startedAt: new Date()
    });
    res.status(200).json({ success: true, data: { session } });
  } catch (err) {
    next(err);
  }
};

exports.stopSession = async (req, res, next) => {
  try {
    const { sessionId, completed } = req.body;
    if (!sessionId) {
      return res.status(400).json({ success: false, message: 'sessionId required' });
    }
    const userId = userIdFrom(req);
    const session = await StudySession.findOne({ _id: sessionId, userId });
    if (!session) return res.status(404).json({ success: false, message: 'Session not found' });

    session.endedAt = new Date();
    session.durationSeconds = Math.round((session.endedAt - session.startedAt) / 1000);
    session.completedDuringSession = !!completed;
    await session.save();
    res.status(200).json({ success: true, data: { session } });
  } catch (err) {
    next(err);
  }
};